# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 08:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc', models.CharField(db_index=True, max_length=12)),
                ('value', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Kredi verilen',
            },
        ),
        migrations.CreateModel(
            name='Credit_Pays',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc', models.CharField(db_index=True, max_length=12)),
                ('value', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Kredi ödenen',
            },
        ),
        migrations.CreateModel(
            name='Dues_Dernek',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc', models.CharField(db_index=True, max_length=12)),
                ('value', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dernek aidat',
            },
        ),
        migrations.CreateModel(
            name='Dues_Sandik',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc', models.CharField(db_index=True, max_length=12)),
                ('value', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Sandik aidat',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('insert_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Gider',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(db_index=True, default='00000000000', max_length=11)),
                ('ad', models.CharField(default='', max_length=50)),
                ('soyad', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('sandik', models.IntegerField(default=0)),
                ('dernek', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=200)),
                ('tel', models.CharField(default='', max_length=15)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2017, 12, 29, 8, 28, 45, 233701, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uyeler',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc', models.CharField(db_index=True, max_length=12)),
                ('odenen_aidat', models.IntegerField(default=0)),
                ('kar_payi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Profit',
            },
        ),
    ]
