# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170210_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Ad',
            new_name='name',
        ),
    ]
