# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170210_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='insert_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dues_dernek',
            name='insert_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dues_sandik',
            name='insert_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='insert_date',
            field=models.DateTimeField(),
        ),
    ]
