# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20170215_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='dernek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='grup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sandik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 12, 39, 56, 85491)),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default='', max_length=15),
        ),
    ]
