# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170222_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grup',
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 12, 41, 54, 43764)),
        ),
    ]
