# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 11:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20170316_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tc',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 11, 23, 39, 209102)),
        ),
    ]
